/* automatically generated by rust-bindgen 0.60.1 */

pub const DPI_NUMBER_AS_TEXT_CHARS: u32 = 172;
pub const DPI_MAX_BASIC_BUFFER_SIZE: u32 = 32767;
pub const DPI_OCI_HTYPE_SVCCTX: u32 = 3;
pub const DPI_OCI_HTYPE_SERVER: u32 = 8;
pub const DPI_OCI_HTYPE_SESSION: u32 = 9;
